#-------------------------------------------------------------------------------------
# This program is a guessing game where the player has to guess a
# number from 1-10 that the computer has randomly chosen.
#
# Created by: Jeff Hejna
# 9/27/14
#
#                       Algorithm
#           1) Have the computer pick a random number.
#           2) Give the player 3 chances to guess the correct number.
#               (computer tells the player to guess higher or lower)
#           3) After 3 turns, the game ends and the player is told the correct number.
#           4) Player guesses correctly-->game stops
#           5) When game finishes, it should ask if the player wants to play again.
#--------------------------------------------------------------------------------------
import random

def player_guess(num1,chances):
        ''' This code takes the random number generated by the computer and stores it into num1.
        The user then has to input their guess and the program compares the users number to the
        random number. The program then prints the appropriate response and returns the result to
        the random_number function.'''
        
        guess = int(input("What is your guess? "))
        if guess == num1:
                result = ("You Win!")
        elif guess != num1 and chances!=2:
            if guess<num1:
                    result = ("Try again, the number is larger")
                    print(result)
            elif guess>num1:
                    result = ("Try again, the number is smaller")
                    print(result)
        else:
                print("You lost. The correct number was",num1)
                result= input("Do you want to play again? Y/N  ")        
                    
        return result            
                
                
    
    
def random_number():
    '''This code creates a random number from 1-10. It also makes it so the user only gets 3
    chances to guess the correct number.It calls the player_guess function while giving it the
    respective random number and chance number. It also asks the user if they want to play again.
    If they do, the program will run again. If not, the program will terminate.'''
    
    num = random.randrange(1,11)
    chance = 0
    while chance<3:                             #keeps track of number of chances
        result = player_guess(num,chance)
        chance+=1
        if result=="You Win!":
                result=input("You won! Do you want to play again? Y/N  ")
                break                          #breaks out of this if statement to go to the next 
    if result=="Y" or result=="y":
            game()
    else:
            print("Game Over")

def game():
    '''This is the main function and it calls the random_number function.'''    
    print("Let's play a game! You have 3 chances to guess the correct number from 1-10")
    random_number()
    

    
game()
    


    
    
    
    

  
    
